### ISSUE TITLE
Should not mark value as incorrect type if type of value is contained in class hierarchy of annotated type

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#624] opened 2023-01-06 09:59 UTC
**Is your feature request related to a problem? Please describe.**
In the last line, PyCharm issues a warning on passing a string. 

However, the value will be coerced into `MyStr` without problems and thus should not be marked as problem here. 
The model can be created no matter if I pass in `MyStr("abc")` or `"abc"`.

```py
import pydantic


class MyStr(str):
    ...


class M(pydantic.BaseModel):
    val: MyStr


def test_():
    assert M(val="abc")

```

**Describe the solution you'd like**
Compare the class hierachy of the annotated and the provided type. Do not mark a value as invalid if the type of the provided value is in the hierarchy of the annotated value.
Like in the example: `MyStr` inherits from `str` so passing a `str` is fine.

**Comment by samuelcolvin** [comment] 2023-01-07 14:31
Duplicate of #140.

**Comment by koxudaxi** [comment] 2023-01-23 12:29
@chbndrhnns 
We are planning the support the list in v2. https://github.com/pydantic/pydantic/issues/4680
currently, we have a work around the feature
https://koxudaxi.github.io/pydantic-pycharm-plugin/type-checker-for-pydantic/
https://github.com/pydantic/pydantic/issues/4680

**Closed by koxudaxi** 2023-01-23 12:29 UTC
