### ISSUE TITLE
Support PY 2023.2 (EAP)

### ISSUE THREAD

**Issue by chbndrhnns** [koxudaxi/pydantic-pycharm-plugin#713] opened 2023-06-02 10:33 UTC
I'd like to see support for 2023.2. I tried compiling it just by changing the version specifiers and it crashes PyCharm 2023.2 EAP 2 after some time.

**Comment by chbndrhnns** [comment] 2023-06-05 10:18
For, this is a way to trigger it with plugin version `0.4.2-231` compiled with `+pluginUntilBuild = 232.*`:

- put cursor on last line after `field_1`
- type `.description`
- PyCharm 232.6734.4 freezes

```py
import pydantic


class M(pydantic.BaseModel):
    field_1 = pydantic.Field(description="abc")
    field_2 = field_1
```

**Comment by koxudaxi** [comment] 2023-06-09 16:24
@chbndrhnns 
I'm sorry for my late response.
I tested the problem.
My environment is not frozen. but I feel a small lag after type `.description`.
I will investigate it.

**Comment by koxudaxi** [comment] 2023-06-09 17:13
@chbndrhnns 
I just tested PyCharm `232.7295.8`. The problem is resolved in the version.
I guess the freeze is a bug in PyCharm.
https://youtrack.jetbrains.com/issue/IDEA-320247
https://youtrack.jetbrains.com/articles/PY-A-233538116/PyCharm-2023.2-EAP-3-232.7295.8-build-Release-Notes

**Comment by koxudaxi** [comment] 2023-06-10 01:58
> I find it working with the mentioned release, as well.

:thinking:  I checked it only IDEA debug mode.
I will check the standalone PyCharm with the build plugin.

I think `field_1` is `class attribute that doesn't have `description` attribute.

Is it correct?

**Comment by koxudaxi** [comment] 2023-06-10 01:59
I got many errors in the unittest with 2023.2.
I should resolve the problem first.
https://github.com/koxudaxi/pydantic-pycharm-plugin/actions/runs/5224676910/jobs/9433167884?pr=717

**Comment by chbndrhnns** [comment] 2023-06-10 15:18
> I think field_1 is class attribute that doesn't have description` attribute.

I'll create a new issue for that.

**Closed** 2023-07-18 15:03 UTC
