### ISSUE TITLE
Warning when using asdict on pydantic dataclasses

### ISSUE THREAD

**Issue by christophelec** [koxudaxi/pydantic-pycharm-plugin#48] opened 2019-08-22 14:28 UTC
Hello, and thanks for the plugin

When using the regular dataclass method [asdict](https://docs.python.org/3/library/dataclasses.html#dataclasses.asdict) on a pydantic dataclass, I get the following warning on Pycharm :

```
'dataclasses.asdict' method should be called on dataclass instances
```

Since pydantic dataclasses are a drop in replacement for dataclasses, it works fine when it is run, so I think the warning should be removed if possible (I'm unfamiliar with Pycharm plugins)

I'm using PyCharm pro 2019.2, with the pydantic plugin in version 0.0.14

To reproduce the issue, open a python file in Pycharm and type:
```
from pydantic.dataclasses import dataclass
from dataclasses import asdict

@dataclass
class Test:
    i: int
    
test_dataclass = Test(0)
asdict(test_dataclass)
```

You will see the warning above on test_dataclass

**Comment by koxudaxi** [comment] 2019-08-23 01:26
@christophelec 
Thank you for your report
I guess the warring is shown by an inspection class for `dataclasses.dataclass `.
We can register a warning message or ignore pre-selected warning messages.
It means we may not stop the warning message directly.
However, I'm going to find a way to resolve the problem.

**Comment by koxudaxi** [comment] 2019-09-02 15:06
I research how to disable the inspection. 
However, I could not find away.

If someone knows the way then, would you tell me it? 

I paste a line that shows the warning.
https://github.com/JetBrains/intellij-community/blob/173989711c4f1e4c16048611f68978b9ec9053ad/python/src/com/jetbrains/python/inspections/PyDataclassInspection.kt#L636

**Comment by samuelcolvin** [comment] 2019-09-02 15:08
Best solution would be to submit a ticket to jetbrains and ask if they can help.

**Comment by koxudaxi** [comment] 2019-09-02 15:11
OK, I issue a ticket to JetBrains.

**Comment by koxudaxi** [comment] 2019-09-02 16:01
I have created a ticket.
https://youtrack.jetbrains.com/issue/PY-37802
I'm waiting for a  response.

**Comment by skewty** [comment] 2019-10-13 01:10
If it is a type issue, can you fool pycharm by telling pycharm the type is a `Union[BaseModel, dataclass]`?  I haven't looked at the code, but this may be a simple cheat.

**Comment by koxudaxi** [comment] 2019-11-01 02:03
@samuelcolvin
Would you please tell me the difference between Pydantic dataclass and Python dataclass?

I talk about this issue with a JetBrains's developer in the JetBrains's issue tracker.
He suggests disabling inspection Pydantic dataclass on Pycharm.
Because of Pydantic dataclass is a different Python dataclass(e.g.: `config`).
And I have promised to create PR. He has accepted to check it.

However, I think if Pydantic dataclass behaves like Python dataclass then, It's better to support Pydantic's dataclass as the same behavior.
I recognize the difference is only the `Config` option.
Is it correct?
Also, I guess that the option doesn't affect the dataclass structure.

Also, I read the sentence in pydantic documents, which say `drop-in replacement`.
Does it mean it perfect compatible?
  `Keep in mind that pydantic.dataclasses.dataclass is a drop-in replacement for dataclasses.dataclass with validation`

I think we have two plans.
1. Disable checking pydantic dataclass in PyCharm.
2. Support pydantic dataclass as the same behavior on Python dataclass in PyCharm. ( accept config argument)

How did you think about it?
If 1. is a better choice then, I will suggest the plan to him.

@dmontagu 
Did you have any thoughts?

**Comment by samuelcolvin** [comment] 2019-11-01 10:20
hi, pydantic dataclasses are **almost** identical to standard dataclasses.

Differences:
* the optional `config` argument to the decorator when creating them
* the following hidden attributes/methods added to the dataclass: `__pydantic_model__`, `__initialised__`, `__validate__`, `__get_validators__`, `__post_init_original__`

In other words, we call `dataclasses._process_class` to create the class same as the normal decorator does with our own `init` function, then add those attributes which are used for validation etc.

if `TYPE_CHECKING` is true, we actually set `pydantic.dataclasses.dataclass` to `dataclasses.dataclass` to aid with type hinting.

Hope that helps, it might help to skim through https://github.com/samuelcolvin/pydantic/blob/master/pydantic/dataclasses.py since it's not that complicated and explains this fully.

**Comment by samuelcolvin** [comment] 2019-11-01 10:22
`dataclasses.asdict()` on a pydantic dataclass should work absolutely fine.

**Comment by koxudaxi** [comment] 2019-11-01 17:58
Thank you very much. It's clear.

**Comment by koxudaxi** [comment] 2020-04-11 16:16
@christophelec @samuelcolvin 

PyCharm 2020.1 has released which can support third-party dataclass library like `pydantic.dataclasses`
This plugin enables the feature, And PyCharm treats `pydantic.dataclasses` as a third-party plugin.
The feature is enabled on plugin version 0.1.0 or later.

Also, Jetbrains developer Semyon Proshev(@sproshev) designed and implemented the feature to PyCharm for communities like us.

Thank you very much.

I put an image which is resolved the problem of the first post.
![screenshot20](https://user-images.githubusercontent.com/630670/79048886-12f2ed80-7c5b-11ea-9ed9-3271f7767f98.png)

**Comment by pauleveritt** [comment] 2020-04-11 16:40
@koxudaxi I've been watching all of the fixes and improvements you've done, waiting for this time when the PyCharm side ships what's needed. I can finally ask: can we do a PyCharm blog post interview with you about this?

**Comment by samuelcolvin** [comment] 2020-04-11 16:43
> @koxudaxi I've been watching all of the fixes and improvements you've done, waiting for this time when the PyCharm side ships what's needed. I can finally ask: can we do a PyCharm blog post interview with you about this?

🥳 🎉 🎉

**Comment by koxudaxi** [comment] 2020-04-11 16:51
@pauleveritt
> can we do a PyCharm blog post interview with you about this?

Sure!! I want to do it :smile:

**Comment by pauleveritt** [comment] 2020-04-11 16:52
@koxudaxi Can you email me, first name dot last name at JetBrains dot com ?

**Comment by koxudaxi** [comment] 2020-04-11 17:09
I have sent an email to you :email:

**Comment by koxudaxi** [comment] 2020-05-03 12:10
This issue was resolved. I close it.

I put an interview link for a history.
https://blog.jetbrains.com/pycharm/2020/04/interview-koudai-aono-author-of-pydantic-plugin-for-pycharm/

**Closed by koxudaxi** 2020-05-03 12:10 UTC
Labels: enhancement, help wanted

**Comment by transfluxus** [comment] 2023-08-02 14:18
Hi,

I still have this warning :/

**Comment by koxudaxi** [comment] 2023-08-05 16:10
@transfluxus 
I couldn't reproduce the warning.
Could you please create a new bug issue with your environment details?

**Comment by transfluxus** [comment] 2023-09-01 10:06
thanks @koxudaxi , all good, I could resolve it
